### ISSUE TITLE
Too much info on 'list' and 'create'

### ISSUE THREAD

**Issue by mustardamus** [mustardamus/lehm#3]
As pointed out by @pateketrueke, if templates have many files or long file/folder-names the output for 'lehm list' and 'lehm create' gets overwhelming:

![](https://cloud.githubusercontent.com/assets/206371/17241054/c5c4971c-5534-11e6-9516-ec1afa1c8c93.png)

For 'list': Show the number of files in the template instead all the file-names, so everything fits on one line, ideally.
For 'command': Don't show the srcPath, just the distPath.

**Comment by pateketrueke** [comment]
Thanks for taking this into account, having minimal info is a matter of preference to me, any path you take to solve it is very appreciated. 👍

**Comment by mustardamus** [comment]
Published new version to NPM. Now it looks like:

![bildschirmfoto 2016-07-29 um 19 19 59](https://cloud.githubusercontent.com/assets/110802/17257310/c86cfb66-55c1-11e6-94a3-7fd168bb32e2.png)
